### ISSUE TITLE
Power Overhaul To-Do List

### ISSUE THREAD

**Issue by freshprogrammer** [freshprogrammer/DCIM#223]
Update power data structures for DCIM roll out

- [x] Create DB script to update DB #228
  - [x] Add UPS table
    - [x] add panel table #218
  - [x] link panel to UPS
  - [x] rename dcim_power to dcim_powerCircuit & dcim_powerCircuitLoc
  - [x] change dcim_powCircuit.panel to panelid
- [x] Update validation and doccumentation on new DBv3 fields #235
 - [x] Fix old power refferences #229
 - [x] Upate panel page to key with panelid #238
 - [x] Fix Circuit add/edit process #230
 - [x] Update Restore data for new DB version #236
 - [x] Create panel page - list by circuits - link to different audit page #243 
 - [x] Create UPS page - list panels - to add/edit panels #226
 - [x] Fix power panel audit processing #260
 - [x] search by panel & UPS #237
 - [x] properly support 208v3p power #220 
 - [x] change 208v3p back to single records - with indicator #256
 - [x] create 208v3p power master lookup #258
 - [x] Double check power records & links updated in logs #257

**Comment by freshprogrammer** [comment]
Finally Done.
